/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parking.view;

import br.com.parking.control.EstacionamentoDAO;
import br.com.parking.control.VeiculosDAO;
import br.com.parking.model.Estacionamento;
import br.com.parking.model.MarcaMoto;
import br.com.parking.model.Marcacarro;
import br.com.parking.model.Veiculo;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author assparremberger
 */
public class CadastrarVeiculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarVeiculo
     */
  
    List<Estacionamento> listaDeEstacionamento;
    List<MarcaMoto> listaDeMotos;
    List<Marcacarro> listaDeCarros;
    
    public CadastrarVeiculo() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jtableVeiculos.getModel();
        jtableVeiculos.setRowSorter(new TableRowSorter(modelo));
        readJTable();
        
        
        carregarEstacionamentos();
        carregarEstacionamentos();
        rbCarro.setSelected(true);
        esconderMoto();
    }
    
    
      private void carregarEstacionamentos(){ 
       /*
        String[] lista = {"Porto Alegre", "Capão da Canoa","Canoas"};
        DefaultComboBoxModel model = new DefaultComboBoxModel(lista);
        cmbCidade.setModel(model);
        */
        
        listaDeEstacionamento = EstacionamentoDAO.listar(); 
        
        DefaultComboBoxModel model = 
                new DefaultComboBoxModel();
        int tamanho = listaDeEstacionamento.size();
        for (int i = 0; i < tamanho ; i++) {
            model.addElement( listaDeEstacionamento.get(i) );
        }
        cmbEstacionamento.setModel(model);
        
    }

     public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jtableVeiculos.getModel();
        modelo.setNumRows(0);
        VeiculosDAO pdao = new VeiculosDAO();

        for (Veiculo p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getCpf(),
                p.getModelo(),
                p.getPlaca(),
                p.getCor(),
                p.getTipo(),
            });

        }

    }
    
    
    private void esconderMoto(){
        cmbMarcaMotos.setVisible(false);
        lblMoto.setVisible(false);
    }
    
    private void aparecerMoto(){
        cmbMarcaMotos.setVisible(true);
        lblMoto.setVisible(true);
    }
    
    private void esconderCarro(){
        cmbMarcaCarros.setVisible(false);
        lblCarro.setVisible(false);
    }
    
    private void aparecerCarro(){
        cmbMarcaCarros.setVisible(true);
        lblCarro.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        buttonGroupCambio = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbMoto = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lblCarro = new javax.swing.JLabel();
        cmbMarcaCarros = new javax.swing.JComboBox();
        lblMoto = new javax.swing.JLabel();
        cmbMarcaMotos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbCombustivel = new javax.swing.JComboBox<>();
        txtCor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableVeiculos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbEstacionamento = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JTextField();
        rbCarro = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Cadastro de Veículos");
        setMinimumSize(new java.awt.Dimension(355, 350));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel2.setText("Modelo:");

        jLabel4.setText("Placa:");

        jLabel5.setText("Tipo:");

        buttonGroupTipo.add(rbMoto);
        rbMoto.setText("Moto");

        lblCarro.setText("Marca:");

        lblMoto.setText("Marca:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMarcaMotos, 0, 361, Short.MAX_VALUE)
                    .addComponent(cmbMarcaCarros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarro)
                    .addComponent(cmbMarcaCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoto)
                    .addComponent(cmbMarcaMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Cor: ");

        jLabel8.setText("Combustivel:");

        cmbCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE...", "GASOLINA", "ÁLCOOL", "DIESEL" }));

        jtableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "CPF", "Modelo", "Placa", "Cor", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableVeiculos);

        jLabel9.setText("CPF Cliente:");

        txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("### ### ###-##"))));

        jLabel6.setText("Estacionamento: ");

        rbCarro.setText("Carro");

        btnSalvar.setText("Cadastrar Carro");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMoto)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbEstacionamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPlaca))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel7)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(txtCor))))
                            .addComponent(btnSalvar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbMoto)
                    .addComponent(jLabel8)
                    .addComponent(cmbCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCarro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEstacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(454, 532));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
         VeiculosDAO vc = new VeiculosDAO();
            Veiculo v = new Veiculo();
                
            v.setCpf(txtCpf.getText());
            v.setPlaca(txtPlaca.getText());
            v.setCor(txtCor.getText());
            v.setCombustivel(cmbCombustivel.getSelectedItem().toString());
        
            if (rbCarro.isSelected()) {
                v.setTipo("Carro");
            }if (rbMoto.isSelected()){
                v.setTipo("Moto");
            }
            
        int posicaoSelecionada = cmbEstacionamento.getSelectedIndex();
        Estacionamento m = listaDeEstacionamento.get(posicaoSelecionada);
        v.setEstacionamento(m);
        
        v.setEstacionamento((Estacionamento) cmbEstacionamento.getSelectedItem() );
        
        int posicaoSelecionadaa = cmbMarcaCarros.getSelectedIndex();
        Marcacarro mc = listaDeCarros.get(posicaoSelecionadaa);
        v.setMarcaCarro(mc);
        
        v.setMarcaCarro((Marcacarro) cmbMarcaCarros.getSelectedItem() );
        
        int posicaoSelecionadaaa = cmbMarcaMotos.getSelectedIndex();
        MarcaMoto mm = listaDeMotos.get(posicaoSelecionadaaa);
        v.setMarcaMoto(mm);
        
        v.setMarcaMoto((MarcaMoto) cmbMarcaMotos.getSelectedItem() );
    
        vc.cadastrar(v);
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupCambio;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JComboBox<String> cmbCombustivel;
    private javax.swing.JComboBox<String> cmbEstacionamento;
    private javax.swing.JComboBox cmbMarcaCarros;
    private javax.swing.JComboBox<String> cmbMarcaMotos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableVeiculos;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblMoto;
    private javax.swing.JRadioButton rbCarro;
    private javax.swing.JRadioButton rbMoto;
    private javax.swing.JTextField txtCor;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
