/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.parking.view;

import br.com.parking.factory.ConnectionFactory02;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.TitledBorder;

/**
 *
 * @author assparremberger
 */
public class SF_PARK extends javax.swing.JFrame {

    /**
     * Creates new form Concessionaria
     */
    public SF_PARK() {
        initComponents();
        testarConexao();
    }
    Connection conn;
    private void testarConexao(){
        try {
            
            
            conn = ConnectionFactory02.getConnection();

            Class.forName(ConnectionFactory02.DRIVER);
            Connection conn = DriverManager.getConnection
                (ConnectionFactory02.conn, ConnectionFactory02.USUARIO, ConnectionFactory02.SENHA);
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    "Verifique se seu servidor de Banco de Dados "
                  + "está on-line!");
        }

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new JSeparator();
        jPanel1 = new JPanel();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jButton5 = new JButton();
        jButton7 = new JButton();
        jLabel1 = new JLabel();
        jSeparator2 = new JSeparator();
        jButton4 = new JButton();
        jButton8 = new JButton();
        jDesktopPane = new JDesktopPane();
        jLabel5 = new JLabel();
        jButton13 = new JButton();
        jButton14 = new JButton();
        jButton15 = new JButton();
        jButton9 = new JButton();
        jButton11 = new JButton();
        jLabel3 = new JLabel();
        jLabel8 = new JLabel();
        btnAtualizar = new JButton();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SF PARK ESTACIONAMENTO");
        setAlwaysOnTop(true);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setLocation(new Point(10, 10));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "NAVEGAR:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setEnabled(false);

        jButton2.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Cadastrar Clientes + .png"))); // NOI18N
        jButton2.setText("Cliente                 ");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Sem Título-1.png"))); // NOI18N
        jButton3.setText("Pesquisar Cliente");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Cadastrar Carros + .png"))); // NOI18N
        jButton5.setText("Veiculo                 ");
        jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/PesquisarCarros.png"))); // NOI18N
        jButton7.setText("Pesquisar Veiculo");
        jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CADASTRAR:");

        jButton4.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Cadastrar Cidades +.png"))); // NOI18N
        jButton4.setText("Estacionamento   ");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Lupa2.png"))); // NOI18N
        jButton8.setText("Estacionamentos");
        jButton8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 90, 220, 480);

        GroupLayout jDesktopPaneLayout = new GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(jDesktopPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(jDesktopPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane);
        jDesktopPane.setBounds(260, 100, 750, 430);

        jLabel5.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/logo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 110, 67);

        jButton13.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Deletar Clientes.png"))); // NOI18N
        jButton13.setText("CLIENTE");
        jButton13.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(670, 540, 160, 60);

        jButton14.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Deletar Cidade.png"))); // NOI18N
        jButton14.setText("ESTACIONAMENTO");
        jButton14.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(260, 540, 200, 60);

        jButton15.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Deletar Veiculos.png"))); // NOI18N
        jButton15.setText("VEICULO                ");
        jButton15.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(470, 540, 188, 60);

        jButton9.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Estoque.png"))); // NOI18N
        jButton9.setText("Minha conta");
        jButton9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(850, 10, 160, 60);

        jButton11.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/Cadastrar atendente.png"))); // NOI18N
        jButton11.setText("ADD Operador");
        jButton11.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(840, 540, 170, 60);

        jLabel3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Bem vindo(a):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 10, 110, 20);

        jLabel8.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("@Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 30, 160, 20);

        btnAtualizar.setFont(new Font("Tahoma", 1, 10)); // NOI18N
        btnAtualizar.setText("ATUALIZAR ESTOQUE");
        btnAtualizar.setAlignmentY(0.0F);
        btnAtualizar.setIconTextGap(0);
        btnAtualizar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(260, 80, 750, 20);

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/br/com/safePark/midia/backgound2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -40, 1030, 840);

        setSize(new Dimension(1043, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        PesquisarVeiculos c = new PesquisarVeiculos();
        jDesktopPane.add(c);
        c.show();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       CadastrarEstacionamento c = new CadastrarEstacionamento();
       jDesktopPane.add(c);
       c.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     PesquisarClientes c = new PesquisarClientes();
     jDesktopPane.add(c);
     c.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       // TODO add your handling code here:
       AtualizarStatus_E_pesquisarVeiculos c = new AtualizarStatus_E_pesquisarVeiculos();
       jDesktopPane.add(c);
       c.show();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       CadastrarVeiculo c = new CadastrarVeiculo();
       jDesktopPane.add(c);
       c.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       CadastrarCliente c = new CadastrarCliente();
       jDesktopPane.add(c);
       c.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
       CadastrarUsuario c = new CadastrarUsuario();
       jDesktopPane.add(c);
       c.show();
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnAtualizarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        AtualizarStatus_E_pesquisarVeiculos ce = new AtualizarStatus_E_pesquisarVeiculos();
        jDesktopPane.add(ce);
        ce.show();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SF_PARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SF_PARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SF_PARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SF_PARK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SF_PARK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAtualizar;
    private JButton jButton11;
    private JButton jButton13;
    private JButton jButton14;
    private JButton jButton15;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton9;
    private JDesktopPane jDesktopPane;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel8;
    private JPanel jPanel1;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
